### ISSUE TITLE
installation: removing grunt dependency

### ISSUE THREAD

**Issue by greut** [inveniosoftware/invenio#1842]
To ease the transition, things can be done this way:
1. Both the overlay and invenio have a bower.json file, one generated and the other being the current one. Part of invenio-demosite installation is to run `inveniomanage bower > bower.json && bower install`.
2. Paths are changed to point to the new location (being `/vendors/<bower-package>/...` according to `.bowerrc`)
3. Then dependencies are removed from invenio's grunt configuration and `bower.json`.
4. Everything that is the overlay can be removed safely from invenio's `bower.json` and grunt.
5. Rince and repeat until invenio's `bower.json` is empty. Then drop grunt.

**TODO**

In the way to simplify the assets/bundling/deploying workflow, let's
- [x] move bundles definition to the python level (#1863)
- [x] generate bundles from the command line (key for deployment) (#1863)
- [x] have one `bower.json` per overlay (generating it like Apache conf) (#1863)
- [x] change invenio-demosite to have and use a bower.json during its setup inveniosoftware/invenio-demosite#28
- [x] fix the paths of all the libraries that are downloaded by the demosite (#1942)
- [x] remove those libraries from invenio's `grunt/copy.js` and `bower.json`. (#1942)
- [ ] figure out what are the remaining libraries and why aren't they in a bundle yet. (#1942)

Related discusions:
- #1767,
- #1806 and
- https://forum.invenio-software.org/t/webassets-vs-grunt/45
