### ISSUE TITLE
roadmap: remove CDS/INSPIRE/etc service-centric code parts

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3126]
**Problem**
Part of Invenio code is completely Cern/Inspire/...-centric or it's a hack.

**Summary**
I make here a summary of all issues/PR connected and all things that maybe can be removed or moved from Invenio core to a specific module/overlay.

- [ ] RFC Dropping INSPIRE-centric legacy code https://github.com/inveniosoftware/invenio/issues/2853
- [ ] global: CFG_CERN_SITE still in code https://github.com/inveniosoftware/invenio/issues/3027
- [ ] records: clean CFG_CERN_SITE, activate refs count https://github.com/inveniosoftware/invenio/pull/3028
- [ ] `git grep "CERN.*hack"`
- [x] `git grep "CERN Bulletin-specific code"`
- [ ] `git grep CFG_BIBFORMAT_FUNCTION_NS`
- [ ] CFG_ADS_SITE, CFG_CERN_SITE, CFG_DEVEL_SITE, CFG_INSPIRE_SITE, CFG_SCOAP3_SITE - `git grep "CFG_.*_SITE"`

**Comment by tiborsimko** [comment]
Superseded by Invenio 3.
