### ISSUE TITLE
roadmap: fully functional Elasticsearch IR

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3232]
- [ ] #2657 finish initial elasticsearch IR implementation
  -  initialise Elasticsearch
  - `invenio.ext.elasticsearch`
  - query parser to Elasticsearch
  - remove json_producer and friends that are not needed anymore
- [ ] #2718 introduce index configurations
  - first with native analysers
- [ ] pluggable Pythonic value enhancers (custom tokenisers)
  - e.g. name permutations
- [ ] remove deprecated xapianutils/solrutils
- [ ] remove native search engine (@jirikuncar)
- [ ] command to index everything from scratch again in Elasticsearch
  - useful in case of crashes
- [ ] plug record upload -> send signal -> catch and enrich JSON in enhancers -> send to Elasticsearch
- [ ] add rank/sort options
  - push number_of_citations as a field
  - "more like this"
- [ ] investigate second-order queries
  - refersto/citedby
  - all papers by e.g. French institutes (inspirehep/invenio#231)
  - parent-child indexing via record linking (but currently both parent and children need to live on the same Elasticsearch shard)

**Comment by tiborsimko** [comment]
Addressed in Invenio 3.
