### ISSUE TITLE
roadmap: legacy removal

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#3233]
These modules are going to disappear/be reimplemented by v2.2.0 (see also: http://simko.home.cern.ch/simko/tmp/invenio-3-roadmap-2015-04-01/invenio-3-legacy-renaissance.png)

This would accelerate achievement of parallel roadmap #3079.
An orthogonal roadmap related to simplifying the code base is #3126.

- [x] WebAlert (@egabancho)
- [x] WebBasket (@egabancho)
- [x] WebComment (@hachreak)
- [x] WebHelp (@egabancho)
- [x] WebJournal (@egabancho)
- [x] WebLinkBack (@jirikuncar)
- [x] WebMessage (@jirikuncar)
- [x] BibSword
- [x] BibCirculation: (see also #2976) (@egabancho)
- [ ] ckeditor
- [x] errorlib (@lnielsen)
- [ ] goto
- [x] httptest (@jirikuncar)
- [ ] dbdump/dbexec
- [x] inveniogc: (see also #3209)
- [ ] solrutils/xapianutils
- [x] ping: shoud be replaced by https://github.com/Runscope/healthcheck (@lnielsen)
- [x] WebSession (@hachreak)
- [ ] WebStyle
- [x] WebSubmit (@jirikuncar)
- [x] BibIngest (@egabancho)
- [x] ELMSubmit (@hachreak)
- [x] OAIHarvest (@jalavik) Moving to `invenio-oaiharvester`
- [ ] BibConvert
- [x] BibClassify (@jalavik) Ready to move to `invenio-classifier`
- [ ] DocExtract  (@jalavik) Moving to external module (extractutils).
- [ ] RefExtract  (@jalavik) Moving to external module (extractutils). (Support for Grobid, bibrank part to be implemented separately)
- [ ] authorextract   (@jalavik) Moving to external module (extractutils).
- [x] BibAuthorList ~~(@kaplun)~~  (@hachreak)
- [x] BibEditMulti (@jmartinm)
- [x] BatchUploader (@lnielsen)
- [ ] BibCatalog 
- [x] BibCheck (@egabancho)
- [x] knowledge (@hachreak)
- [x] BibMerge (@jmartinm)
- [x] BibEdit (@jmartinm)
- [x] PDFChecker (@kaplun)
- [x] hepdata (@kaplun)
- [ ] plotextractor (@jalavik)
- [x] workflows (@jirikuncar) Moved to `invenio-workflows`
- [x] BibMatch (@kaplun) Replaced by `invenio-matcher`.
- [ ] BibUpload (@crepererum)
- [x] BibAuthority (@tiborsimko)

invenio.legacy:
- authorextract @jalavik 
- bibcatalog @jirikuncar
- bibconvert @jirikuncar
- bibdocfile @jirikuncar
- bibexport 
- bibrecord 
- bibsched
- bibupload
- ckeditor
- docextract @jalavik 
- goto 
- httptest
- miscutil
- oairepository
- refextract @jalavik 
- search_engine
- webaccess
- websearch
- webstyle
- wsgi

invenio.modules:
- access
- authorprofiles
- authors
- classifier
- collections
- communities
- converter
- dashboard
- deposit
- editor
- encoder
- exporter
- jsonalchemy
- knowledge
- merger
- multimedia
- oaiharvester
- oairepository 
- records
- redirector
- refextract
- scheduler
- search
- sequencegenerator
- sorter
- tags
- textminer
- tickets
- unapi
- upgrader

**Comment by kaplun** [comment]
Suppose I would like to contribute removal of BibClassify. This module has been partially ported (in the sense that there are wrapping views, models and CLI in `invenio.modules.classifier`. What shall I do there? Shall we simply preserve the models so that at least the DB table contents are not lost in case one day the module is reimplemented?

cc: @tiborsimko, @jirikuncar.

**Comment by jirikuncar** [comment]
> What shall I do there?

Probably remove `invenio/legacy/bibclassify` and moving needed functionality to `invenio.modules.classifier`.

> Shall we simply preserve the models so that at least the DB table contents are not lost in case one day the module is reimplemented?

According to http://simko.home.cern.ch/simko/tmp/invenio-3-roadmap-2015-04-01/invenio-3-legacy-renaissance.png INSPIRE is leading the effort, hence I don't know how much resources you have and when new `invenio-classifier` module will be ready including upgrade recipes.

**Comment by kaplun** [comment]
That's the thing. Supposed we are going to tackle this in the far future (e.g. three months or so) and that is going to use a completely different approach, I guess it's not worth saving even the code under `invenio.modules.classifier`. Maybe indeed just the models, to allow at some point to implement a migration recipe (if needed).

Same thing for e.g. `refextract`. The source code could disappear, but it's maybe worth to preserve the text-based knowledge bases? Or we shall rather kill them as well, and in case recover them from git history?

**Comment by jirikuncar** [comment]
You can delete the models, but don't create an upgrade recipe that removes the data.

**Comment by kaplun** [comment]
Further question: `(doc|ref|author)extract` *is* used by `BibCatalog` which is used by `BibEdit` which is due for 2.3. I might try to drop `BibCatalog` in a way that `BibEdit` survive. OK?

**Comment by lnielsen** [comment]
Note, ``bibcheck`` is used by ``bibmatch`` which isn't schedule for removal until 2.3. 

**Proposal:**
1) Remove bibmatch in 2.2
or 
2) Remove bibcheck in 2.3

Ping @kaplun

**Comment by kaplun** [comment]
I start to think we should rather kill everything and good night. We are not going to use release 2.2 anytime for our production or labs services, after all.
For 2.2 the foreseen existing modules are: `oairepository`, `search_engine`, `websearch`, `webdoc`, `webstat`, `bibindex`, `bibrank`, `bibsort`, `bibsched`, `webaccess`, `bibexport`, `bibformat`(?), `bibedit`, `bibmatch`, `bibrecord`, `bibupload`, `bibauthority`, `bibdocfile`.

But would like to hear the opinion of @jalavik and @jmartinm who are going to be back only next week though.

**Comment by jirikuncar** [comment]
`bibformat` is already out

**Comment by egabancho** [comment]
Is there any reason why WebStat is not in the list? 

Some of the modules marked to be deleted are used inside it, it would make things easier if we delete this one first.

**Comment by kaplun** [comment]
The list was built from Tibor's mind map. Some modules were retained for 2.2 there:
> oairepository, search_engine, websearch, webdoc, webstat, bibindex, bibrank, bibsort, bibsched, webaccess, bibexport, bibformat(?), bibedit, bibmatch, bibrecord, bibupload, bibauthority, bibdocfile.

but indeed, given yesterday announcement of Tibor, we could actually decide all together to go full speed and simply kill all legacy for 2.2 (although they were not properly deprecated in 2.1)

**Comment by jalavik** [comment]
Just FYI, I am looking at bibclassify now.

**Comment by crepererum** [comment]
I'm currently working on wiping out `bibsched` and `bibupload` because they where destroyed by the new Record API and would mostly need a rewrite. No sure yet if you replace `bibsched` with an celery task or if we insert the records directly into the system, because we could use transactions now. (depends on the switch to InnoDB or PostgreSQL).

**Comment by jirikuncar** [comment]
@crepererum you can remove `bibupload` and leave `bibsched` untouched for now.

**Comment by hachreak** [comment]
@lnielsen can you update the list for websession and inveniogc? thanks :D 
https://github.com/inveniosoftware/invenio/commit/9d5cf934307f3ace9e62a9cb09a60a87f1855566

**Comment by jirikuncar** [comment]
Closed via c4c292f and newborn Invenio-3.0a1.
