### ISSUE TITLE
roadmap: simplified records module

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#3283]
- [x] **storage** 
  - [x] removal of `invenio.modules.records`
  - SQLAlchemy model - PostgreSQL JSONB field if available (see "[invenio-records](https://github.com/jirikuncar/invenio-records)")
  - [x] release *Invenio-Records*
  - [x] ~~create an upgrade recipe to migrate to new *Invenio-Records* storage (added column with version, re-submit data)~~ recommended way is to re-upload data to new instance
- [x] **indexing**
  - [x] removal of BibIndex, BibRank, BibSort
  - [x] write signal handlers to launch ~~bibindex~~ Elastic search tasks
  - [x] create configurable `es` instance ~~(`invenio.ext.es`)~~ in *Invenio-Search*.
  - [x] prepare mapping configuration for Elasticsearch (https://github.com/inveniosoftware/es-jsonschema/pull/1 by @nharraud)
- [x] **quering** 
  - [x] native IR (later Elasticsearch) for indexed records 
  - [x] SQLAlchemy + JSONB for exact database searches if needed (#2379)
  - [x] create new search API: `invenio.modules.search.api:Query('title:higgs')[10:20]` based on https://github.com/inveniosoftware/invenio/issues/2478#issuecomment-71647267 from January 27th
- [x] **cli** 
  - [x] `inveniomanage records create` Flask-Script/Click
  - [x] `inveniomanage records patch/update`
  - [x] removal of *uploader* (#3365)
  - [x] removal of *BibUpload*
  - [x] create registry of format convertors (https://github.com/inveniosoftware/invenio-records/pull/3)
- [x] **data conversion** 
  - [x] "[DoJSON](https://github.com/jirikuncar/dojson)", XSLT, JSONPatch depending on data format
  - [x] release *DoJSON* (inveniosoftware/dojson#18 @tiborsimko)
  - [x] proof read `dojson.contrib.marc21` (@egabancho)
  - [x] discuss possibilities for extending/editing DoJSON rules
- [x] **formatting**
  - [x] ~~port `bfe_*` formatting elements to Jinja (#3244)~~ **invenio-records-ui** by @lnielsen 
  - [x] ~~collection count for restricted collections?~~ (updated: new UI without counts)
  - [x] ~~update formatter templates (#2662)~~ new **invenio-search-js** and **invenio-search-ui** by @drjova 

--
If you would like to test current implementation check #3307.

```
# Test on 100 Zenodo records
$ wget 'https://zenodo.org/search?ln=en&p=&of=xm&rg=100' -O data.xml
$ workon invenio & cdvirtualenv
$ pip install --pre invenio-records>=1.0.0a1
$ cat data.xml | dojson do marc21 | inveniomanage records create

# or with demosite data
$ cat invenio/testsuite/data/demo_record_marc_data.xml | dojson do marc21 | inveniomanage records create
```

--

#### Notes on terminology

**data** - bibliographic metadata about records
**schema** - *JSON-Schema* describing **data** in `$ref`
**context** - additional mappings from JSON to an RDF model (*JSON-LD*).

--
cc @egabancho @kaplun @tiborsimko @lnielsen @crepererum

**Comment by kaplun** [comment]
Thanks @jirikuncar for having initiated this roadmap-issue.

I believe we should also consider as part of this roadmap:
* Handling of documents (especially since JSONAlchemy disappears)
* Handling of pidstore (in particular documentation with tutorial/patterns): http://invenio.readthedocs.org/en/latest/search.html?q=pidstore&check_keywords=yes&area=default is currently empty
* Handling of signals (in particular documentation with tutorial/patterns)

**Comment by kaplun** [comment]
* Handling of conflicts when two records are being touched at the same time

**Comment by jirikuncar** [comment]
> Handling of conflicts when two records are being touched at the same time

SQLAlchemy does that already for us (http://docs.sqlalchemy.org/en/latest/orm/versioning.html).

**Comment by jirikuncar** [comment]
Updated roadmap information with links to related issues and packages. I'm closing this issue as all points have existing solution.
