### ISSUE TITLE
global: remove legacy dependency

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3508]
List of modules to check:
- [ ] invenio #3470 
- [x] invenio-access (only `dbquery`)
- [ ] invenio-accounts (`webuser`)
- [x] invenio-annotations
- [x] invenio-base (only `dbquery`)
- [x] invenio-classifier
- [x] invenio-client
- [x] invenio-cloudconnector
- [x] invenio-collections
- [ ] invenio-comments (`bibrecord`, `dbquery`, `search_engine`) inveniosoftware/invenio-comments#7
- [ ] invenio-communities (`search_engine`, `bibrecord`, `bibupload`) inveniosoftware/invenio-communities#7
- [x] invenio-deposit
- [x] invenio-documents
- [ ] invenio-ext (`bibdocfile`, `registry`, `webpage`, `webuser`, `wsgi`) inveniosoftware/invenio-ext#4
- [x] invenio-formatter (only `dbquery`)
- [x] invenio-groups
- [x] invenio-jsonschemas
- [x] invenio-knowledge (only `dbquery` in upgrades)
- [x] invenio-messages (only `dbquery`)
- [x] invenio-mobile
- [x] invenio-news
- [x] invenio-oaiharvester (only `dbquery` in upgrades)
- [x] invenio-oauth2server (only `dbquery` in upgrades)
- [x] invenio-oauthclient (only `dbquery` in upgrades)
- [x] invenio-pages
- [x] invenio-pidstore
- [x] invenio-previewer
- [x] invenio-previewer-ispy
- [x] invenio-query-parser
- [ ] invenio-records (`bibrecord`) inveniosoftware/invenio-records#18 inveniosoftware/invenio-records#36
- [x] invenio-redirector (`bibdocfile`, `search_engine`) inveniosoftware/invenio-redirector#2
- [ ] invenio-search (`bibindex`, `bibrecord`, `dbquery`, `miscutil`, `refextract`, `search_engine`, `webuser`) inveniosoftware/invenio-search#18 inveniosoftware/invenio-search#15  inveniosoftware/invenio-search#17
- [ ] invenio-sequencegenerator (`bibrecord`, `bibsched`, `dbquery`, `search_engine`) inveniosoftware/invenio-sequencegenerator#1
- [x] invenio-tags (`search_engine`) inveniosoftware/invenio-tags#12 inveniosoftware/invenio-tags#7 inveniosoftware/invenio-tags#13 inveniosoftware/invenio-tags#11
- [x] invenio-unapi
- [x] invenio-upgrader (only `dbquery` in upgrades)
- [ ] invenio-utils (`bibdocfile`)
- [x] invenio-webhooks
- [ ] invenio-workflows (`bibconvert`, `bibsched`, `dbquery`) inveniosoftware/invenio-workflows#14 inveniosoftware/invenio-workflows#8

**Comment by jirikuncar** [comment]
@hachreak maybe you can re-sort them in +/- topological order.

**Comment by tiborsimko** [comment]
All legacy components have been removed in Invenio 3.
