### ISSUE TITLE
releases: make releases of all modules prior to v3.1 release

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#3916]
> Checked: Release PR created
> Crossed-out: Released on PyPI

- [x] invenio-admin: v1.1.1
- [x] invenio-app: v1.1.0
- [x] invenio-assets: v1.1.2 (inveniosoftware/invenio-assets#95)
- [x] invenio-accounts v1.1.0 (inveniosoftware/invenio-accounts#275)
- [x] invenio-access: v1.1.0
- [x] invenio-base: v1.0.2
- [x] invenio-i18n: v1.1.1
- [x] invenio-logging: v1.1.0
- [x] invenio-oauthclient v1.1.2
- [x] invenio-indexer: v1.0.1
- [x] invenio-oaiserver: v1.0.3 inveniosoftware/invenio-oaiserver#160)
- [x] invenio-records: v1.0.1
- [x] invenio-theme: v1.1.2 (inveniosoftware/invenio-theme#129)
- [x] invenio-records-rest: v1.3.0 
- [ ] datacite v1.0.2 (inveniosoftware/datacite#42, inveniosoftware/datacite#45)
- [x] flask-webpack: v1.0.1
- [ ] idutils: v1.1.1 (inveniosoftware/idutils#45)
- [x] pytest-invenio: v1.1.0 inveniosoftware/pytest-invenio#31)

**Comment by lnielsen** [comment]
Modules released
