### ISSUE TITLE
global: update tested ElasticSearch throughout all repositories

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio#3961]
`.travis.yml` files across all Invenio repositories should have consistent ElasticSearch versions that they're tested against, and preferably the latest possible version at the moment.

**Comment by jorikvankemenade** [comment]
- [ ] inveniosoftware/invenio-oaiserver#172
- [ ] inveniosoftware/invenio-indexer#108
- [ ] inveniosoftware/invenio-stats#91
- [ ] inveniosoftware/invenio-index-migrator#4
- [ ] inveniosoftware/invenio-marc21#66
- [ ] inveniosoftware/invenio-records-rest#272
- [ ] inveniosoftware/invenio#3962
- [ ] inveniosoftware/invenio-search#182
