### ISSUE TITLE
tests: fix build error due to requirements builder problem (4 repositories)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#4004]
Subtasks:
- [x] inveniosoftware/invenio-app#63
- [x] inveniosoftware/invenio-config#46
- [x] inveniosoftware/invenio-formatter#64
- [x] inveniosoftware/invenio-records#215

**Comment by ppanero** [comment]
All fixed.
