### ISSUE TITLE
tests: fix problems due to Sphinx v3.x (3 repositories)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#4005]
Subtasks:
- [x] inveniosoftware/invenio-access#174
- [x] inveniosoftware/invenio-previewer#114

Likely candidates for Sphinx 3 problems:
- [x] inveniosoftware/invenio-records-rest#295

Pin Sphinx in ``setup.py`` to ``<3``.

**Comment by ppanero** [comment]
All done
